package panda3.model;

import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.serverless.DynamoDBAdapter;

import java.io.IOException;
import java.util.List;
import java.util.Map;

@DynamoDBTable(tableName = "participants_table")
public class Participant {
    private String id;
    private String name;
    private String surname;

    public Participant(){
    }


    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }


    public void setId(String id) {
        this.id = id;
    }


    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return name;
    }


    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName = "surname")
    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }
}
